-- MySQL Script generated by MySQL Workbench
-- Mon Aug 25 19:45:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema livraria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema livraria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `livraria` DEFAULT CHARACTER SET utf8 ;
USE `livraria` ;

-- -----------------------------------------------------
-- Table `livraria`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livraria`.`Autor` (
                                                  `CodAu` INT NOT NULL AUTO_INCREMENT,
                                                  `Nome` VARCHAR(40) NOT NULL,
    PRIMARY KEY (`CodAu`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livraria`.`Assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livraria`.`Assunto` (
                                                    `codAs` INT NOT NULL AUTO_INCREMENT,
                                                    `Descricao` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`codAs`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livraria`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livraria`.`Livro` (
                                                  `Codl` INT NOT NULL AUTO_INCREMENT,
                                                  `Titulo` VARCHAR(40) NOT NULL,
    `Editora` VARCHAR(40) NOT NULL,
    `Edicao` INT NOT NULL,
    `AnoPublicacao` VARCHAR(4) NOT NULL,
    PRIMARY KEY (`Codl`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livraria`.`Livro_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livraria`.`Livro_Autor` (
                                                        `Livro_Codl` INT NOT NULL,
                                                        `Autor_CodAu` INT NOT NULL,
                                                        PRIMARY KEY (`Livro_Codl`, `Autor_CodAu`),
    INDEX `Livro_Autor_FKIndex2_idx` (`Autor_CodAu` ASC) VISIBLE,
    CONSTRAINT `Livro_Autor_FKIndex1`
    FOREIGN KEY (`Livro_Codl`)
    REFERENCES `livraria`.`Livro` (`Codl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `Livro_Autor_FKIndex2`
    FOREIGN KEY (`Autor_CodAu`)
    REFERENCES `livraria`.`Autor` (`CodAu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livraria`.`Livro_Assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livraria`.`Livro_Assunto` (
                                                          `Livro_Codl` INT NOT NULL,
                                                          `Assunto_CodAs` INT NOT NULL,
                                                          PRIMARY KEY (`Livro_Codl`, `Assunto_CodAs`),
    INDEX `Livro_Assunto_FKIndex2_idx` (`Assunto_CodAs` ASC) VISIBLE,
    CONSTRAINT `Livro_Assunto_FKIndex1`
    FOREIGN KEY (`Livro_Codl`)
    REFERENCES `livraria`.`Livro` (`Codl`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `Livro_Assunto_FKIndex2`
    FOREIGN KEY (`Assunto_CodAs`)
    REFERENCES `livraria`.`Assunto` (`codAs`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
